config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  get 'flats', to: 'flats#index'

  get 'flats/:id', to: 'flats#show', as: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require 'open-uri'

class FlatsController < ApplicationController
  def index
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    uri = URI.open(url)
    @flats = JSON.parse(uri.read)
  end

  def show
    flat_id = params[:id] # => 145
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    uri = URI.open(url)
    @flats = JSON.parse(uri.read)
    @flats = @flats.select { |flat| flat["id"] == flat_id.to_i }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>
<div class="d-flex justify-content-center">
<% @flats.each do |flat| %>
    <div class="card mx-3" style="width: 18rem;">
    <img src="<%= flat['imageUrl']%>" class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title"><%= flat['name'] %></h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><i class="fa-solid fa-location-dot"></i><%= flat['lat'] %>, <%= flat['lng'] %></li>
        <li class="list-group-item"><i class="fa-solid fa-euro-sign"></i> <%= flat['price'] %></li>
    </ul>
    <div class="card-body">
        <%= link_to "See More", show_path(flat['id']), class: "btn btn-danger" %>
    </div>
    </div>
<% end %>
</div>

app/views/flats/show.html.erb
<% @flats.each do |flat|  %>
<h1><%= flat['name'] %></h1>
<div class="card mb-3">
  <img src="<%= flat['imageUrl'] %>" class="card-img-top w-50" alt="...">
  <div class="card-body">
    <h5 class="card-title"><%= flat['name'] %></h5>
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    <%= link_to "Back", flats_path, class: "btn btn-sm btn-info" %>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStatic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>